name: Build C++ Project for Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 检出代码

    - name: Set up build tools
      run: sudo apt-get install build-essential  # 安装 GCC 和构建工具

    - name: Build the project
      run: |
        mkdir build
        cd build
        # 使用 g++ 编译，-I 选项告诉编译器包含相关目录
        g++ -I../include -I. -o my_project ../main.cpp ../schoolMap.cpp  # 编译并生成 my_project 可执行文件
        ./my_project  # 运行构建出来的可执行文件

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: build/my_project  # 上传构建的可执行文件
